apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
  namespace: airflow-elastic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airflow-worker
  template:
    metadata:
      labels:
        app: airflow-worker
    spec:
      containers:
      - name: worker
        image: apache/airflow:2.10.4-python3.11
        command:
        - airflow
        - celery
        - worker
        envFrom:
        - configMapRef:
            name: airflow-config
        - secretRef:
            name: airflow-secrets
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
