apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: airflow-elastic
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  AIRFLOW_WWW_USER_USERNAME: "airflow"
  AIRFLOW_WWW_USER_PASSWORD: "airflow"
  POSTGRES_USER: "airflow"
  POSTGRES_PASSWORD: "airflow"
  POSTGRES_DB: "airflow"
